In [4]:
import numpy as np
# Create matrices
A= np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
#Addition
C = A + B
#Subtraction
D = A - B
#Multiplication(element-wise)
E = A * B
#Matrix multiplication
F = np.dot(A,B)# or A @ B
#Transpose
A_transpose = A.T
print("--Addition--")
print(C)
print("\n--Subtraction--")
print(D)
print("\n--Element-wise Multiplication--")
print(E)
print("\n--Matrix Multiplication--")
print(F)
print("\n--Transpose--")
print(A_transpose)

import numpy as np
#creste a sample matrix
X =np.array([[1,2,3],[4,5,6],[7,8,9]])
#Perform SVD
U,S,VT =np.linalg.svd(X)
#choode the number of component to keep (eg.2)
n_components=2
# reconstructed the matrix with reduced dimentions
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("\n--Original Matrix--")
print(X)
print("\n--Reconstructed Matrix (with reduced dimensions)--")
print(X_reconstructed)



--Addition--
[[ 6  8]
 [10 12]]

--Subtraction--
[[-4 -4]
 [-4 -4]]

--Element-wise Multiplication--
[[ 5 12]
 [21 32]]

--Matrix Multiplication--
[[19 22]
 [43 50]]

--Transpose--
[[1 3]
 [2 4]]

--Original Matrix--
[[1 2 3]
 [4 5 6]
 [7 8 9]]

--Reconstructed Matrix (with reduced dimensions)--
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
